name: Full-year calendar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.isocalendar.fullyear.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_isocalendar: yes
  plugin_isocalendar_duration: full-year